### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by neonpolaris** [darkwinternight/roomba-wifi#2]
I like this project and will be implementing something like soon. Maybe I'm blind, but I don't actually see any code posted here. The links to documentation are very useful to write up my own, but the readme suggests this part was done already. Can you point me in the right direction?

**Comment by otherguy** [comment]
That is true. All the work is done and right this second I'm starting my Roomba from work -- but I had no time to prepare the code and the photos etc. and actually update the documentation. 

Maybe I can get around to working a bit on this today 🤔
